In [31]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import random

In [12]:
# Read the CSV file
df = pd.read_csv("../data/Occupancy_Estimation.csv")

# Display the first few rows of the DataFrame
df

# df['Datetime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'])

,Date,Time,S1_Temp,S2_Temp,S3_Temp,S4_Temp,S1_Light,S2_Light,S3_Light,S4_Light,S1_Sound,S2_Sound,S3_Sound,S4_Sound,S5_CO2,S5_CO2_Slope,S6_PIR,S7_PIR,Room_Occupancy_Count
0,2017/12/22,10:49:41,24.94,24.75,24.56,25.38,121,34,53,40,0.08,0.19,0.06,0.06,390,0.769231,0,0,1
1,2017/12/22,10:50:12,24.94,24.75,24.56,25.44,121,33,53,40,0.93,0.05,0.06,0.06,390,0.646154,0,0,1
2,2017/12/22,10:50:42,25.00,24.75,24.50,25.44,121,34,53,40,0.43,0.11,0.08,0.06,390,0.519231,0,0,1
3,2017/12/22,10:51:13,25.00,24.75,24.56,25.44,121,34,53,40,0.41,0.10,0.10,0.09,390,0.388462,0,0,1
4,2017/12/22,10:51:44,25.00,24.75,24.56,25.44,121,34,54,40,0.18,0.06,0.06,0.06,390,0.253846,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10124,2018/01/11,08:58:07,25.06,25.13,24.69,25.31,6,7,33,22,0.09,0.04,0.06,0.08,345,0.000000,0,0,0
10125,2018/01/11,08:58:37,25.06,25.06,24.69,25.25,6,7,34,22,0.07,0.05,0.05,0.08,345,0.000000,0,0,0
10126,2018/01/11,08:59:08,25.13,25.06,24.69,25.25,6,7,34,22,0.11,0.05,0.06,0.08,345,0.000000,0,0,0
10127,2018/01/11,08:59:39,25.13,25.06,24.69,25.25,6,7,34,22,0.08,0.08,0.10,0.08,345,0.000000,0,0,0
10128,2018/01/11,09:00:09,25.13,25.06,24.69,25.25,6,7,34,22,0.08,0.05,0.06,0.08,345,0.000000,0,0,0

In [53]:
preds = [] 
#split my datarames into two dataframes, one for training and one for test
train = df.loc[0:9000]
test = df.loc[9000:10000]

#iterate through the rows of the dataframe, if the S6_PIR field is 0 and the S7_PIR field is 0, then append 0 to the preds list, otherwise append 1
for row in df.iterrows():
    if row[1]['S6_PIR'] == 0 and row[1]['S7_PIR'] == 0:
        preds.append(0)
    else:
        preds.append(random.choice([1,2,3]))

#calculate the accuracy of the predictions
accuracy = sum(preds[i] == df.loc[i]['Room_Occupancy_Count'] for i in range(0, len(preds))) / len(preds)
accuracy

0.8452956856550499